package corendonlmsv2.view.panels;

import corendonlmsv2.connectivity.LanguageController;
import corendonlmsv2.connectivity.LanguageController.Languages;
import corendonlmsv2.main.CorendonLMSv2;
import corendonlmsv2.main.util.MiscUtil;
import corendonlmsv2.model.ActionLog;
import corendonlmsv2.model.UserAccount;
import corendonlmsv2.model.UserAccount.UserRoles;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;


/**
 * Asks the user for their credentials and signs them in if correct
 *
 * @author Sjoerd Banen
 */
public class Login extends JPanel implements ActionListener, MouseListener
{

    /**
     * Contains the file name to be opened upon clicking the help button,
     * which provides help
     */
    private static final String HELP_FILENAME = "Usermanual.pdf";
    
    /**
     * Creates new form Login
     */
    public Login()
    {
        initComponents();
        
        setBackground(CorendonLMSv2.DEFAULT_BACKCOLOR);
        
        jLabel1.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        jLabel2.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        jLabel3.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        jLabel4.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        forgotLabel.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        forgotLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        registerListeners();
    }
    
    private void registerListeners()
    {
        forgotLabel.addMouseListener(this);
        signInButton.addActionListener(this);
        helpButton.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent ae)
    {
        final Object source = ae.getSource();
        
        if (source == signInButton)
        {
            String username = usernameField.getText();
            String password = new String(passwordField.getPassword());
            
            UserRoles role = UserAccount.validateUserRole(username, password);
            UserAccount.setCurrent(new UserAccount(username, null, role, false));
            
            LanguageController.setLanguage((Languages) 
                        languageComboBox.getSelectedItem());
            
            if (role != UserRoles.UNAUTHORIZED)
            {
                new ActionLog(UserAccount.getCurrent(), "Signed in").insert();
                
                JPanel panel;
                
                if (role == UserRoles.DESK_EMPLOYEE)
                {
                    panel = new DeskHub();
                } else if (role == UserRoles.MANAGER)
                {
                    panel = new ManagerHub();
                } else if (role == UserRoles.ADMIN)
                {
                    panel = new AdminHub();
                } else
                {
                    return;
                }
                
                CorendonLMSv2.MAIN_FRAME.displayPanel(panel);
                MiscUtil.showMessage(LanguageController.getString("signedInAs") 
                        + UserAccount.getCurrent());
            } else
            {
                MiscUtil.showMessage(
                        LanguageController.getString("incorrectCredentials"));
            }
        } else if (source == helpButton)
        {
            try
            {
                Desktop.getDesktop().open(new File(HELP_FILENAME));
            } catch (IOException ex)
            {
                MiscUtil.showMessage(this, "Documentation could not be "
                        + "found.\n\n" + ex.getMessage());
            }
        }
    }

    @Override
    public void mouseClicked(MouseEvent me)
    {
        if (me.getSource() == forgotLabel)
        {
            MiscUtil.showMessage(LanguageController.getString("forgotPassword"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JButton();
        forgotLabel = new javax.swing.JLabel();
        languageComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Welcome! Please sign in to get started.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username:");

        usernameField.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password:");

        passwordField.setPreferredSize(new java.awt.Dimension(6, 30));

        signInButton.setText("Sign in");
        signInButton.setPreferredSize(new java.awt.Dimension(63, 35));

        forgotLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        forgotLabel.setForeground(new java.awt.Color(0, 0, 255));
        forgotLabel.setText("Forgot password?");

        languageComboBox.setModel(new DefaultComboBoxModel(Languages.values()));

        jLabel4.setText("Language:");

        helpButton.setText("Help");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(forgotLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotLabel)
                .addGap(18, 18, 18)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(helpButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgotLabel;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox languageComboBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signInButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public void mousePressed(MouseEvent me)
    {
        //Intentionally left blank
    }

    @Override
    public void mouseReleased(MouseEvent me)
    {
        //Intentionally left blank
    }

    @Override
    public void mouseEntered(MouseEvent me)
    {
        //Intentionally left blank
    }

    @Override
    public void mouseExited(MouseEvent me)
    {
        //Intentionally left blank
    }
}
