/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package corendonlmsv2.view.panels;

import corendonlmsv2.main.CorendonLMSv2;
import corendonlmsv2.model.ActionLog;
import corendonlmsv2.model.UserAccount;
import corendonlmsv2.view.PanelViewer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Emile Pels
 */
public class ManagerHub extends JPanel implements ActionListener
{

    /**
     * Creates new form Hub
     */
    public ManagerHub()
    {
        initComponents();

        setBackground(CorendonLMSv2.DEFAULT_BACKCOLOR);

        welcomeLabel.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        welcomeLabel.setText(String.format("Welcome back, %s! What would you"
                + " like to do?", UserAccount.getCurrent()));

        registerListeners();
    }

    /**
     * Registers listeners for all appropriate components
     */
    private void registerListeners()
    {
        signOutButton.addActionListener(this);
        logsButton.addActionListener(this);
        graphsButton.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent ae)
    {
        Object source = ae.getSource();
        JPanel panel;        
        
        if (source == signOutButton)
        {
            new ActionLog(UserAccount.getCurrent(), "Signed out").insert();
            
            UserAccount.setCurrent(null);
            panel = new Login();
        } else if (source == logsButton)
        {
            panel = new LogViewer(this);
        } else if (source == graphsButton)
        {
            //TODO
            return;
        } else
        {
            return;
        }
        
        CorendonLMSv2.MAIN_FRAME.displayPanel(panel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        welcomeLabel = new javax.swing.JLabel();
        signOutButton = new javax.swing.JButton();
        logsButton = new javax.swing.JButton();
        graphsButton = new javax.swing.JButton();

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcomeLabel.setText("welcomeLabel");

        signOutButton.setText("Sign out");

        logsButton.setBackground(new java.awt.Color(150, 40, 40));
        logsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logsButton.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        logsButton.setIcon(new ImageIcon("resources" + PanelViewer.PATH_SEPERATOR + "Logs.png"));
        logsButton.setText("View logs");
        logsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logsButton.setIconTextGap(10);
        logsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        graphsButton.setBackground(new java.awt.Color(150, 40, 40));
        graphsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        graphsButton.setForeground(CorendonLMSv2.DEFAULT_FORECOLOR);
        graphsButton.setIcon(new ImageIcon("resources" + PanelViewer.PATH_SEPERATOR + "Graph.png"));
        graphsButton.setText("View graphs");
        graphsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        graphsButton.setIconTextGap(10);
        graphsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(graphsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(signOutButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(graphsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton graphsButton;
    private javax.swing.JButton logsButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
